car_shop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('car_shop_app.urls', namespace='car_shop_app')),
]

car_shop_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # Домашняя страница
    url(r'^$', views.index, name='index'),
    # Просмотр
    url(r'^(?P<entity>[a-z]+)/$', views.show),
    # Авто
    url(r'^cars/new/$', views.cars_new, name='cars_new'),
    url(r'^cars/(?P<id>\d+)/edit/$', views.cars_edit, name='cars_edit'),
    # Клиенты
    url(r'^customers/new/$', views.customers_new, name='customers_new'),
    url(r'^customers/(?P<id>\d+)/edit/$', views.customers_edit, name='customers_edit'),
    # Аксессуары
    url(r'^accessories/new/$', views.accessories_new, name='accessories_new'),
    url(r'^accessories/(?P<id>\d+)/edit/$', views.accessories_edit, name='accessories_edit'),
    # Удаление
    url(r'^(?P<entity>[a-z]+)/delete/(?P<id>\d+)/$', views.delete),
]

car_shop_app/models.py
from django.db import models

class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    fio = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    tel = models.CharField(max_length=20)

    def __str__(self):
        return str(self.fio)


class Employee(models.Model):
    id = models.AutoField(primary_key=True)
    fio = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    salary = models.FloatField(default=0)

    def __str__(self):
        return str(self.fio)


class Provider(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    tel = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return str(self.name)

class Accessory(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    provider = models.ForeignKey(Provider)
    count = models.IntegerField(null=True)

    def __str__(self):
        return str(self.name + ' ' + str(self.provider))


class Car(models.Model):
    TYPE_ENGINE_CHOICES = (
        ('БНЗ', 'Бензин'),
        ('ДЗЛ', 'Дизель'),
        ('ГБР', 'Гибрид'),
        ('ЭЛК', 'Электро'),
    )

    BODY_CHOICES = (
        ('СДН', 'Седан'),
        ('ХТЧ', 'Хэтчбек'),
        ('ВНД', 'Внедорожник'),
        ('УНВ', 'Универсал'),
        ('КУП', 'Купе'),
        ('МНВ', 'Минивэн'),
    )

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    type_engine = models.CharField(
        max_length=3,
        choices=TYPE_ENGINE_CHOICES,
        default='БНЗ',
    )

    body = models.CharField(
        max_length=3,
        choices=BODY_CHOICES,
        default='СДН',
    )
    year = models.PositiveSmallIntegerField(null=True)
    price = models.FloatField(default=0)
    count = models.IntegerField(null=True)
    image = models.CharField(max_length=100, null=True)

    def __str__(self):
        return str(self.name)


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer)
    employee = models.ForeignKey(Employee)
    car = models.ForeignKey(Car)
    date = models.DateField(null=True)
    cost = models.FloatField(default=0)

    def __str__(self):
        return str(str(self.car) + ' ' + str(self.customer))


class MoreAboutOrder(models.Model):
    id = models.AutoField(primary_key=True)
    accessory = models.ForeignKey(Accessory)
    order = models.ForeignKey(Order)
    count = models.IntegerField(null=True)

    def __str__(self):
        return str(str(self.order) + ' ' + str(self.accessory))

car_shop_app/forms.py
from django import forms
from .models import Customer, Employee, Order, Provider, Accessory, Car, MoreAboutOrder
import re
from django.core.exceptions import ValidationError

class CustomerForm(forms.ModelForm):

    def clean_fio(self):
        data = self.cleaned_data['fio']
        if not re.match(r'[A-Za-zА-Яа-яЁё\s]+$', data):
            raise ValidationError('Введите корректное ФИО')

        return data

    def clean_address(self):
        data = self.cleaned_data['address']
        if not re.match(r'[0-9A-Za-zА-Яа-яЁё\-\.\/\s]+$', data):
            raise ValidationError('Введите корректный адрес')

        return data

    def clean_tel(self):
        data = self.cleaned_data['tel']
        if not re.match(r'(\+?\d[- .]*){7,13}$', data):
            raise ValidationError('Введите корректный телефон')

        return data

    class Meta:
        model = Customer
        fields = '__all__'

        labels = {
            'fio': ('ФИО'),
            'address': ('Адрес'),
            'tel': ('Телефон'),
        }

        widgets = {
            'fio': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'address': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'tel': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'pattern': '(\+?\d[- .]*){7,13}'})
        }


class AccessoryForm(forms.ModelForm):

    def clean_name(self):
        data = self.cleaned_data['name']
        if not re.match(r'[A-Za-zА-Яа-яЁё\s]+$', data):
            raise ValidationError('Введите корректное название')

        return data


    class Meta:
        model = Accessory
        fields = '__all__'

        labels = {
            'name': ('Название'),
            'provider': ('Поставщик'),
            'price': ('Цена'),
            'count': ('Количество'),
        }

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'provider': forms.Select(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'price': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'type':'number', 'step':'0.01'}),
            'count': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'type':'number'})
        }


class CarForm(forms.ModelForm):

    def clean_name(self):
        data = self.cleaned_data['name']
        if not re.match(r'[\dA-Za-zА-Яа-яЁё\s]+$', data):
            raise ValidationError('Введите корректное название')

        return data

    def clean_year(self):
        data = self.cleaned_data['year']
        if data < 1900 or data > 2017:
            raise ValidationError('Введите корректный год')

        return data

    class Meta:
        model = Car
        fields = ['name', 'type_engine', 'body', 'year', 'price', 'count']

        labels = {
            'name': ('Название'),
            'type_engine': ('Двигатель'),
            'body': ('Кузов'),
            'year': ('Год'),
            'price': ('Цена'),
            'count': ('Количество'),
        }

        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'type_engine': forms.Select(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'body': forms.Select(attrs={'class':'form-control', 'aria-describedby':'basic-addon1'}),
            'year': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'type':'number'}),
            'price': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'type':'number', 'step':'0.01'}),
            'count': forms.TextInput(attrs={'class':'form-control', 'aria-describedby':'basic-addon1', 'type':'number'})
        }

car_shop_app/views.py
from django.shortcuts import render
import sqlite3
from django.http import HttpResponseRedirect
from .models import Customer, Employee, Order, Provider, Accessory, Car, MoreAboutOrder
from .forms import CustomerForm, AccessoryForm, CarForm
from django.shortcuts import get_object_or_404
from .filters import CarFilter


def customers_new(request):
    if request.method == "POST":
        form = CustomerForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/customers/')
    else:
        form = CustomerForm()
    return render(request, 'car_shop_app/customers_new_edit.html', {'form': form})


def customers_edit(request, id):
    customer = get_object_or_404(Customer, id=id)
    if request.method == "POST":
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/customers/')
    else:
        form = CustomerForm(instance=customer)
    return render(request, 'car_shop_app/customers_new_edit.html', {'form': form})


def accessories_new(request):
    if request.method == "POST":
        form = AccessoryForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/accessories/')
    else:
        form = AccessoryForm()
    return render(request, 'car_shop_app/accessories_new_edit.html', {'form': form})


def accessories_edit(request, id):
    accessory = get_object_or_404(Accessory, id=id)
    if request.method == "POST":
        form = AccessoryForm(request.POST, instance=accessory)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/accessories/')
    else:
        form = AccessoryForm(instance=accessory)
    return render(request, 'car_shop_app/accessories_new_edit.html', {'form': form})


def cars_new(request):
    if request.method == "POST":
        form = CarForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/cars/')
    else:
        form = CarForm()
    return render(request, 'car_shop_app/cars_new_edit.html', {'form': form})


def cars_edit(request, id):
    car = get_object_or_404(Car, id=id)
    if request.method == "POST":
        form = CarForm(request.POST, instance=car)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return HttpResponseRedirect('/cars/')
    else:
        form = CarForm(instance=car)
    return render(request, 'car_shop_app/cars_new_edit.html', {'form': form})


def dict_factory(cursor, row):
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d


def index(request):
 """Домашняя страница приложения Learning Log"""
 return render(request, 'car_shop_app/index.html')


def show(request, entity):
    """Просмотр"""
    con = sqlite3.connect("db.sqlite3")
    con.row_factory = dict_factory
    cursor = con.cursor()

    templates = {'cars': 'car_shop_app/cars.html', 
            'accessories': 'car_shop_app/accessories.html',
            'customers': 'car_shop_app/customers.html',
            }

    sql = {'accessories': ("SELECT acs.id as id, acs.name as name, prv.name as provider, price, count "
    	                   "FROM car_shop_app_accessory acs "
                           "INNER JOIN car_shop_app_provider prv ON acs.provider_id = prv.id"),
            'customers': ("SELECT * FROM car_shop_app_customer"),
            }

    if entity != 'cars':
        cursor.execute(sql[entity])
        rows = cursor.fetchall()
        context = {'values': rows}
    else:
        cars = Car.objects.all()
        cars_filter = CarFilter(request.GET, queryset=cars)
        context = {'values': cars_filter}
    
    return render(request, templates[entity], context)


def delete(request, id, entity):
    """Удаление сотрудника"""
    con = sqlite3.connect("db.sqlite3")
    con.row_factory = dict_factory
    cursor = con.cursor()

    sql = {'cars': ("DELETE "
                       "FROM car_shop_app_car "
                       "WHERE id = " + str(id)), 
            'accessories': ("DELETE "
                       "FROM car_shop_app_accessory "
                       "WHERE id = " + str(id)),
            'customers': ("DELETE "
                          "FROM car_shop_app_customer "
                          "WHERE id = " + str(id)),
            }
    cursor.execute(sql[entity])

    con.commit()
    return HttpResponseRedirect('/' + entity)

car_shop_app/templates/car_shop_app/accessories.html
{% extends "car_shop_app/base.html" %}

{% block header %}{% endblock header %}
{% block content %}
<!-- Page Content -->

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

<div class="title" style="display:inline-block;">
<h3>Аксессуары</h3>
</div>
<div class="add_button" style="display:inline-block;">
<a href="{% url 'car_shop_app:accessories_new' %}"><span class="glyphicon glyphicon-plus"></span></button></a>
</div>
<div class="container-full">


    <script type="text/javascript">
                $(document).ready(function() {
                $('#example').DataTable();
                    } );
    </script>
    <table id="example" class="table table-striped table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Название</th>
            <th>Поставщик</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>DELETE/EDIT</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Название</th>
            <th>Поставщик</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>DELETE/EDIT</th>
        </tr>
        </tfoot>
        <tbody style="font-family: Arial;">
        {%for accessory in values%}
        <tr>
            <td>{{accessory.name}}</td>
            <td>{{accessory.provider}}</td>
            <td>{{accessory.price}}</td>
            <td>{{accessory.count}}</td>
            <td>
                <div class="delete" style="display:inline-block;">
            <form method="delete" id="delete" action="delete/{{accessory.id}}" onsubmit="return confirm('Вы действительно хотите удалить элемент?');">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-remove"></span></button></p>
            </form>
                    </div>
                <div class="edit" style="display:inline-block;">
                <form method="get" id="edit" action="{{accessory.id}}/edit/">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-pencil"></span></button></p>
            </form>
                    </div>
            </td>

        </tr>
        {%endfor%}
        </tbody>
    </table>
   

</div> <!-- /container full -->
    <!-- /.container -->

{% endblock content %}

car_shop_app/templates/car_shop_app/accessories_new_edit.html
{% extends 'car_shop_app/base.html' %}

{% block content %}
<div class="col-lg-12 text-center v-center">
    <h3>Аксессуар</h3>
    <br>
    <form role="form" class="col-lg-12" method="POST"> {% csrf_token %}
        {% for field in form %}
        <div class="input-group col-sm-offset-4 col-sm-4">
        	<span class="input-group-addon" id="basic-addon1">
            {{ field.label_tag }}
            </span>
            {{ field }}
        </div>
        <strong>{{ field.errors.as_text }}</strong>
        <br>
        {% endfor %}
        <button type="submit" class="save btn btn-primary"> 
        	<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save
        </button>
    </form>
</div>
{% endblock %}

car_shop_app/templates/car_shop_app/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Автомагазин</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/stylestore.css' %}">


</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
                aria-expanded="false" aria-controls="navbar">
        </button>
	    <a class="navbar-brand" href="{% url 'car_shop_app:index' %}">Автомагазин</a>
      </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        <div class="page-header" style="border: 0px solid #3962b5;">
	      {% block header %}{% endblock header %}
        </div>
        <div>
	      {% block content %}{% endblock content %}
        </div>

      </div> <!-- /container -->


</body>

</html>

car_shop_app/templates/car_shop_app/cars.html
{% extends "car_shop_app/base.html" %}

{% block header %}{% endblock header %}
{% block content %}

{% load widget_tweaks %}
<!-- Page Content -->

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <form method="get">
    <div class="well">
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
          <strong>Название:</strong>
          {% render_field values.form.name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          <strong>Двигатель:</strong>
          {% render_field values.form.type_engine class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          <strong>Кузов:</strong>
          {% render_field values.form.body class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          <strong>Год:</strong>
          {% render_field values.form.year class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          <strong>Цена:</strong>
          {% render_field values.form.price class="form-control" %}
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Поиск
      </button>
    </div>
  </form>

<div class="title" style="display:inline-block;">
<h3>Авто</h3>
</div>
<div class="add_button" style="display:inline-block;">
<a href="{% url 'car_shop_app:cars_new' %}"><span class="glyphicon glyphicon-plus"></span></button></a>
</div>
<div class="container-full">


    <script type="text/javascript">
                $(document).ready(function() {
                $('#example').DataTable();
                    } );
    </script>
    <table id="example" class="table table-striped table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>Название</th>
            <th>Двигатель</th>
            <th>Кузов</th>
            <th>Год</th>
            <th>Цена</th>
            <th>Кол-во</th>
            <th>DELETE/EDIT</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>Название</th>
            <th>Двигатель</th>
            <th>Кузов</th>
            <th>Год</th>
            <th>Цена</th>
            <th>Кол-во</th>
            <th>DELETE/EDIT</th>
        </tr>
        </tfoot>
        <tbody style="font-family: Arial;">
        {%for car in values.qs%}
        <tr>
            <td>{{ car.name }}</td>
            <td>{{ car.get_type_engine_display }}</td>
            <td>{{ car.get_body_display }}</td>
            <td>{{ car.year }}</td>
            <td>{{ car.price }}</td>
            <td>{{ car.count }}</td>
            <td>
                <div class="delete" style="display:inline-block;">
            <form method="delete" id="delete" action="delete/{{car.id}}" onsubmit="return confirm('Вы действительно хотите удалить элемент?');">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-remove"></span></button></p>
            </form>
                    </div>
                <div class="edit" style="display:inline-block;">
                <form method="get" id="edit" action="{{car.id}}/edit/">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-pencil"></span></button></p>
            </form>
                    </div>
            </td>

        </tr>
        {%endfor%}
        </tbody>
    </table>
   

</div> <!-- /container full -->
    <!-- /.container -->

{% endblock content %}

car_shop_app/templates/car_shop_app/cars_new_edit.html
{% extends 'car_shop_app/base.html' %}

{% block content %}
<div class="col-lg-12 text-center v-center">
    <h3>Авто</h3>
    <br>
    <form role="form" class="col-lg-12" method="POST"> {% csrf_token %}
        {% for field in form %}
        <div class="input-group col-sm-offset-4 col-sm-4">
        	<span class="input-group-addon" id="basic-addon1">
            {{ field.label_tag }}
            </span>
            {{ field }}
        </div>
        <strong>{{ field.errors.as_text }}</strong>
        <br>
        {% endfor %}
        <button type="submit" class="save btn btn-primary"> 
        	<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save
        </button>
    </form>
</div>
{% endblock %}

car_shop_app/templates/car_shop_app/customers.html
{% extends "car_shop_app/base.html" %}

{% block header %}{% endblock header %}
{% block content %}
<!-- Page Content -->

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

<div class="title" style="display:inline-block;">
<h3>Клиенты </h3>
</div>
<div class="add_button" style="display:inline-block;">
<a href="{% url 'car_shop_app:customers_new' %}"><span class="glyphicon glyphicon-plus"></span></button></a>
</div>
<div class="container-full">


    <script type="text/javascript">
                $(document).ready(function() {
                $('#example').DataTable();
                    } );
    </script>
    <table id="example" class="table table-striped table-hover" cellspacing="0" width="100%">
        <thead>
        <tr>
            <th>ФИО</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>DELETE/EDIT</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <th>ФИО</th>
            <th>Адрес</th>
            <th>Телефон</th>
            <th>DELETE/EDIT</th>
        </tr>
        </tfoot>
        <tbody style="font-family: Arial;">
        {%for customer in values%}
        <tr>
            <td>{{ customer.fio }}</td>
            <td>{{ customer.address }}</td>
            <td>{{ customer.tel }}</td>
            <td>
                <div class="delete" style="display:inline-block;">
            <form method="delete" id="delete" action="delete/{{customer.id}}" onsubmit="return confirm('Вы действительно хотите удалить элемент?');">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-remove"></span></button></p>
            </form>
                    </div>
                <div class="edit" style="display:inline-block;">
                <form method="get" id="edit" action="{{customer.id}}/edit/">
            <p><button type="submit" class="btn btn-default btn-xs">
                <span class="glyphicon glyphicon-pencil"></span></button></p>
            </form>
                    </div>
            </td>

        </tr>
        {%endfor%}
        </tbody>
    </table>
   

</div> <!-- /container full -->
    <!-- /.container -->

{% endblock content %}

car_shop_app/templates/car_shop_app/customers_new_edit.html
{% extends 'car_shop_app/base.html' %}

{% block content %}
<div class="col-lg-12 text-center v-center">
    <h3>Клиент</h3>
    <br>
    <form role="form" class="col-lg-12" method="POST"> {% csrf_token %}
        {% for field in form %}
        <div class="input-group col-sm-offset-4 col-sm-4">
        	<span class="input-group-addon" id="basic-addon1">
            {{ field.label_tag }}
            </span>
            {{ field }}
        </div>
        <strong>{{ field.errors.as_text }}</strong>
        <br>
        {% endfor %}
        <button type="submit" class="save btn btn-primary"> 
        	<span class="glyphicon glyphicon-ok" aria-hidden="true"></span> Save
        </button>
    </form>
</div>
{% endblock %}

car_shop_app/templates/car_shop_app/index.html
{% extends "car_shop_app/base.html" %}
{% load staticfiles %}

{% block header %}{% endblock header %}
{% block content %}
<!-- Page Content -->
<style>
.destacados{
    padding: 20px 0;
    text-align: center;
}
.destacados > div > div{
    padding: 10px;
    border: 1px solid transparent;
    border-radius: 4px;
    transition: 0.2s;
}
.destacados > div:hover > div{
    margin-top: -10px;
    border: 1px solid rgb(200, 200, 200);
    box-shadow: rgba(0, 0, 0, 0.1) 0px 5px 5px 2px;
    background: rgba(200, 200, 200, 0.1);
    transition: 0.5s;
}
</style>

<div class="container" style="width: 70%; margin-top: -30px;">
    <div class="row destacados">
        <div class="col-md-4">
            <div>
                <img src="static/image/car.jpg" alt="Repairs" class="img-circle img-thumbnail">
                <h2>Авто</h2>
                <a href="/cars" class="btn btn-primary" title="Repairs">Перейти »</a>
            </div>
        </div>

        <div class="col-md-4">
            <div>
                <img src="static/image/spares.jpg" alt="Spares" class="img-circle img-thumbnail">
                <h2>Аксессуары</h2>
                <a href="/accessories" class="btn btn-primary" title="Spares">Перейти »</a>
            </div>
        </div>

        <div class="col-md-4">
            <div>
                <img src="static/image/customers.jpg" alt="Customers" class="img-circle img-thumbnail">
                <h2>Клиенты</h2>
                <a href="/customers" class="btn btn-primary" title="Customers">Перейти »</a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}